all:
  vars:
    ansible_user: sysadmin

  children:
    ubuntu:
      hosts:
        ubu-canary01:
          ansible_host: 192.168.56.31
        ubu-prod01:
          ansible_host: 192.168.56.32

    rocky:
      hosts:
        rocky-canary01:
          ansible_host: 192.168.56.41
        rocky-prod01:
          ansible_host: 192.168.56.42

    canary:
      hosts:
        ubu-canary01:
        rocky-canary01:

    production:
      hosts:
        ubu-prod01:
        rocky-prod01:
